### ISSUE TITLE
Menu displays under ArcDPS windows

### ISSUE THREAD

**Issue by SamMackrill** [xvwyh/SquadRoles#1]
This can make it hard/impossible to select

**Comment by xvwyh** [comment]
Attach a screenshot showcasing the issue, please. I have no idea what menu you are talking about.

**Comment by SamMackrill** [comment]
![image](https://github.com/user-attachments/assets/ba878884-46d7-4510-9bec-d76e4d151dc0)

**Comment by xvwyh** [comment]
This is not possible to fix, ArcDPS draws itself as an overlay on top of the game. You have several options on how to deal with this:
- Move your ArcDPS windows to a different place.
- Press Alt-Shift-H to toggle the visibility of all ArcDPS windows.
- Enable "clicking windows requires modifiers" option in ArcDPS, that way you'll have to hold down Alt-Shift to interact with any ArcDPS windows, and the windows will be transparent to clicks otherwise, so you'll be able to click the context menu buttons through them.
