### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by elguilleinge** [xvwyh/SquadRoles#5]
Hi, first at all absolutly qol simple & great extension, that said yesterday release make gw2 crash.
Again love this extension and I hope to use it again soon.

**Comment by xvwyh** [comment]
Can you provide any more details about when it crashes? What were you doing when it crashed? An arcdps crash log?

**Comment by xvwyh** [comment]
Just did a convergence to be sure and didn't crash.

**Comment by elguilleinge** [comment]
i have arcdps_squadroles.dll in main gw2 folder (always works in there) and when load character selection screen after 2/3 seconds the game closes but if i remove the extension the game works as usually, im doing something wrong?

**Comment by xvwyh** [comment]
Did the addon update to the new version for you since yesterday? ArcDPS is supposed to automatically update it when you get to character select. Perhaps it fails to do that due to permissions or something? Normally arcdps addon dlls are placed inside bin64, I have no idea what happens if it isn't there, I never tested it for I didn't think it would even load plugins from elsewhere other than bin64. Try moving it there and see what happens. Try downloading the new update manually and see if that works: https://github.com/xvwyh/SquadRoles/releases/latest

**Comment by elguilleinge** [comment]
It's working again for me, apparently the problem was that I had the version of vc redist 14.33, I updated to 14.40 and it works again without any problem, I'm sorry for the waste of time (I really like this extension), tyvm

**Comment by xvwyh** [comment]
Oh, I see. Yeah, I did update the compiler on my end. I'll leave this issue up for the time being, in case someone else visits with the same issue, so that they know how to solve it: redownload and intall https://aka.ms/vs/17/release/vc_redist.x64.exe.

**Comment by gadtwo** [comment]
it also doesn't matter where the file is located, in the root folder or bin64
the main thing is to check that you have deleted the previous version (otherwise I threw it into the root folder, but forgot to delete old it from bin64)
